services:
  snowflake_snowflake_sample_data:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.snowflake_sample_data
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $SNOWFLAKE_SNOWFLAKE_SAMPLE_DATA_HASURA_SERVICE_TOKEN_SECRET
      JDBC_SCHEMAS: $SNOWFLAKE_SNOWFLAKE_SAMPLE_DATA_JDBC_SCHEMAS
      JDBC_URL: $SNOWFLAKE_SNOWFLAKE_SAMPLE_DATA_JDBC_URL
      OTEL_EXPORTER_OTLP_ENDPOINT: $SNOWFLAKE_SNOWFLAKE_SAMPLE_DATA_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $SNOWFLAKE_SNOWFLAKE_SAMPLE_DATA_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 4745:8080
