services:
  chinook_postgres:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.postgres
    environment:
      CLIENT_CERT: $CHINOOK_POSTGRES_CLIENT_CERT
      CONNECTION_URI: $CHINOOK_POSTGRES_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $CHINOOK_POSTGRES_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $CHINOOK_POSTGRES_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $CHINOOK_POSTGRES_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 25060:8080
